### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by gdussert** [amathislab/wildclip#1]
Hello, 

For the inference, you give this command : 
```
python eval_clip.py \
-F config_files/wildclip_vitb16_t1.yml \
-I ../data/test_dataset_crops_single_animal_template_captions_T1T8T10.csv \
-C captions/serengeti_test_queries_T1T8T10_nattr_1.txt \
-M ../results/wildclip_vitb16_t1/wildclip_vitb16_t1_last_ckpt.pth
```

But it looks like `captions/serengeti_test_queries_T1T8T10_nattr_1.txt` is not in the Zenodo or this repo.

Thanks

**Comment by gabeva** [comment]
Thanks for pointing this out
Missing files have been added with [00af528](https://github.com/amathislab/wildclip/commit/00af5289e95d7340cf09baaadea8d7d1a754bb95)
